### ISSUE TITLE
Building against ICU 59 failed

### ISSUE THREAD

**Issue by rbn42** [compiz-reloaded/libcompizconfig#2]
Hi,

```
In file included from /usr/include/unicode/utypes.h:38:0,
                 from /usr/include/unicode/ucnv_err.h:88,
                 from /usr/include/unicode/ucnv.h:52,
                 from /usr/include/libxml2/libxml/encoding.h:31,
                 from /usr/include/libxml2/libxml/parser.h:810,
                 from /usr/include/libxslt/transform.h:15,
                 from compiz.cpp:26:
/usr/include/unicode/umachine.h:347:13: error: ‘char16_t’ does not name a type
     typedef char16_t UChar;
             ^
```

Building against ICU 58 succeeded.
[A similar error can be found here.](https://bbs.archlinux.org/viewtopic.php?pid=1707952#p1707952)

**Comment by XRevan86** [comment]
Try ```CXXFLAGS="-std=g++11"```.

Not sure if requiring C++11 in autoconf here would be the right call when a version of a dependency of a dependency wants it…

**Comment by brossaip** [comment]
Hi!
I have the same error, but I can not downgrade to ICU 58 because of KDE dependencies
